<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        $this->command->info('🔑 Creating comprehensive permissions for Filament + Spatie setup...');

        // Define permission groups with both Filament and custom permissions
        $permissionGroups = [
            'stories' => [
                'description' => 'Story management permissions',
                'permissions' => [
                    // Filament Resource permissions (auto-generated by Shield)
                    'view_any_story',
                    'view_story',
                    'create_story',
                    'update_story',
                    'restore_story',
                    'restore_any_story',
                    'replicate_story',
                    'reorder_story',
                    'delete_story',
                    'delete_any_story',
                    'force_delete_story',
                    'force_delete_any_story',

                    // Custom story permissions
                    'list stories',
                    'show stories',
                    'create stories',
                    'update stories',
                    'delete stories',
                    'publish stories',
                    'unpublish stories',
                    'feature stories',
                    'archive stories',
                    'schedule stories',
                ],
            ],
            'categories' => [
                'description' => 'Category management permissions',
                'permissions' => [
                    // Filament Resource permissions
                    'view_any_category',
                    'view_category',
                    'create_category',
                    'update_category',
                    'restore_category',
                    'restore_any_category',
                    'replicate_category',
                    'reorder_category',
                    'delete_category',
                    'delete_any_category',
                    'force_delete_category',
                    'force_delete_any_category',

                    // Custom category permissions
                    'list categories',
                    'show categories',
                    'create categories',
                    'update categories',
                    'delete categories',
                    'manage category order',
                ],
            ],
            'tags' => [
                'description' => 'Tag management permissions',
                'permissions' => [
                    // Filament Resource permissions
                    'view_any_tag',
                    'view_tag',
                    'create_tag',
                    'update_tag',
                    'restore_tag',
                    'restore_any_tag',
                    'replicate_tag',
                    'reorder_tag',
                    'delete_tag',
                    'delete_any_tag',
                    'force_delete_tag',
                    'force_delete_any_tag',

                    // Custom tag permissions
                    'list tags',
                    'show tags',
                    'create tags',
                    'update tags',
                    'delete tags',
                    'merge tags',
                ],
            ],
            'users' => [
                'description' => 'User management permissions',
                'permissions' => [
                    // Filament Resource permissions
                    'view_any_user',
                    'view_user',
                    'create_user',
                    'update_user',
                    'restore_user',
                    'restore_any_user',
                    'replicate_user',
                    'reorder_user',
                    'delete_user',
                    'delete_any_user',
                    'force_delete_user',
                    'force_delete_any_user',

                    // Custom user permissions
                    'list users',
                    'show users',
                    'create users',
                    'update users',
                    'delete users',
                    'impersonate users',
                    'reset user passwords',
                    'activate users',
                    'deactivate users',
                ],
            ],
            'members' => [
                'description' => 'Member management permissions',
                'permissions' => [
                    // Filament Resource permissions
                    'view_any_member',
                    'view_member',
                    'create_member',
                    'update_member',
                    'restore_member',
                    'restore_any_member',
                    'replicate_member',
                    'reorder_member',
                    'delete_member',
                    'delete_any_member',
                    'force_delete_member',
                    'force_delete_any_member',

                    // Custom member permissions
                    'list members',
                    'show members',
                    'create members',
                    'update members',
                    'delete members',
                    'activate members',
                    'suspend members',
                    'ban members',
                    'verify members',
                    'manage member subscriptions',
                    'view member analytics',
                ],
            ],
            'roles' => [
                'description' => 'Role & Permission management',
                'permissions' => [
                    // Filament Resource permissions (Shield)
                    'view_any_role',
                    'view_role',
                    'create_role',
                    'update_role',
                    'delete_role',
                    'delete_any_role',

                    // Custom role permissions
                    'list roles',
                    'show roles',
                    'create roles',
                    'update roles',
                    'delete roles',
                    'assign roles',
                    'revoke roles',
                ],
            ],
            'permissions' => [
                'description' => 'Permission management',
                'permissions' => [
                    // Filament Resource permissions
                    'view_any_permission',
                    'view_permission',
                    'create_permission',
                    'update_permission',
                    'delete_permission',
                    'delete_any_permission',

                    // Custom permission management
                    'list permissions',
                    'show permissions',
                    'create permissions',
                    'update permissions',
                    'delete permissions',
                    'sync permissions',
                ],
            ],
            'analytics' => [
                'description' => 'Analytics and reporting permissions',
                'permissions' => [
                    'view analytics',
                    'view member analytics',
                    'view story analytics',
                    'view category analytics',
                    'view tag analytics',
                    'view user analytics',
                    'export analytics',
                    'export reports',
                    'view dashboard',
                    'view advanced analytics',
                    'manage analytics settings',
                ],
            ],
            'system' => [
                'description' => 'System administration permissions',
                'permissions' => [
                    'view logs',
                    'manage settings',
                    'backup system',
                    'restore system',
                    'clear cache',
                    'run migrations',
                    'manage queues',
                    'view system health',
                    'manage maintenance mode',
                    'access developer tools',
                ],
            ],
            'content' => [
                'description' => 'Content management permissions',
                'permissions' => [
                    'moderate content',
                    'approve content',
                    'reject content',
                    'feature content',
                    'schedule content',
                    'bulk operations',
                    'import content',
                    'export content',
                    'manage media',
                    'manage uploads',
                ],
            ],
            'notifications' => [
                'description' => 'Notification management permissions',
                'permissions' => [
                    'send notifications',
                    'schedule notifications',
                    'manage notification templates',
                    'view notification logs',
                    'broadcast announcements',
                ],
            ],
            'api' => [
                'description' => 'API access permissions',
                'permissions' => [
                    'access api',
                    'manage api tokens',
                    'view api logs',
                    'manage api settings',
                ],
            ],
        ];

        // Create permissions by group
        foreach ($permissionGroups as $groupName => $groupData) {
            $this->command->info("Creating {$groupName} permissions...");

            foreach ($groupData['permissions'] as $permissionName) {
                $permission = Permission::firstOrCreate([
                    'name' => $permissionName,
                    'guard_name' => 'web'
                ]);
            }

            $this->command->info("  ✓ Created " . count($groupData['permissions']) . " {$groupName} permissions");
        }

        // Create some additional Filament-specific permissions if you have custom pages/widgets
        $this->createFilamentSpecificPermissions();

        // Clear the cache after creating permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        $totalPermissions = Permission::count();
        $this->command->info("✅ Created {$totalPermissions} permissions successfully!");
    }

    private function createFilamentSpecificPermissions(): void
    {
        $this->command->info('Creating Filament-specific permissions...');

        // Dashboard and Widget permissions
        $filamentPermissions = [
            'page_Dashboard',
            'widget_MemberOverviewWidget',
            'widget_MemberEngagementWidget',
            'widget_TopMembersWidget',
            'widget_ReadingInsightsWidget',
            'widget_MemberDemographicsWidget',
        ];

        foreach ($filamentPermissions as $permissionName) {
            Permission::firstOrCreate([
                'name' => $permissionName,
                'guard_name' => 'web'
            ]);
        }

        $this->command->info("  ✓ Created " . count($filamentPermissions) . " Filament-specific permissions");
    }
}
